---

- name: Check directories
  file: path=/{{ item.dir }} state=directory
        owner={{ item.dir_owner | default('root') }} group={{ item.dir_group | default('adm') }} mode={{ item.dir_mode | default('0750') }}
  with_items: 
    - "{{ kibana_install_template | default ([]) }}"
    - "{{ kibana_install_file | default ([]) }}"
    - "{{ log | default ([]) }}"

- name: Check templates
  template: src={{ item.dir }}/{{ item.name }}.j2 dest=/{{ item.dir }}/{{ item.name }}
            owner={{ item.file_owner | default('root') }} group={{ item.file_group | default('adm') }} mode={{ item.file_mode | default('0660') }}
  with_items: 
    - "{{ kibana_install_template | default ([]) }}"
  notify: "{{ item.after_update | default('') }} {{ service_name }}"

- name: Check files
  copy: src={{ item.dir }}/{{ item.name }} dest=/{{ item.dir }}/{{ item.name }}
        owner={{ item.file_owner | default('root') }} group={{ item.file_group | default('adm') }} mode={{ item.file_mode | default('0640') }}
  with_items: 
    - "{{ kibana_install_file | default ([]) }}"
  notify: "{{ item.after_update | default('') }} {{ service_name }}"