---

- name: Check dependencies
  package: name={{ item }} state=present
  with_items:
    - "{{ dependencies | default ([]) }}"

- name: Check repo keys
  apt_key: url={{ item }} state=present
  with_items:
    - "{{ repo_keys | default ([]) }}"

- name: Check repositories
  apt_repository: repo={{ item }} state=present update_cache=yes #filename={{ service_name }}
  with_items:
    - "{{ repos | default ([]) }}"

- name: Check app installation
  package: name={{ item }} state=present
  with_items:
    - "{{ install_packages | default ([]) }}"
