---

- include: install.yml
  when: "{{ service_name }}_enabled"
  tags: 
    - "{{ service_name }}"

- include: configure.yml
  when: "{{ service_name }}_enabled"
  tags: 
    - "{{ service_name }}"
    - "{{ service_name }}_conf"

- name: Service is running and enabled
  service: name={{ service_name }} state=running enabled=yes
  when: "{{ service_name }}_enabled"
  with_items:
    - "{{ service_name }}"
  tags: 
    - "{{ service_name }}"
